

server:
  port: 80



spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/sb-auth/sb-auth-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
 #   driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto:  none
    show-sql: true


datasource:
  flyway:
    url: jdbc:h2:file:~/sb-auth/sb-auth-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    schemas: PUBLIC
#   driver-class-name: org.h2.Driver
#   validate-on-migrate: false
#   locations: classpath:/db/migration
#   check-location: true




flyway:
  baseline-on-migrate: true
  url: jdbc:h2:file:~/sb-auth/sb-auth-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  user: sa
  password:
  schemas: PUBLIC
# validate-on-migrate: false
# locations: classpath:/db/migration
# check-location: true



logging:
  level:
    root: info
    sbauth: debug
    db.migration: debug
    org.springframework.web: debug
    org.flywaydb.core.Flyway: debug
    org.flywaydb.core.Flyway.*: debug
 #   org.springframework.beans.factory: debug


debug: true
trace: false














