

server:
  port: 80
#  context-path: /v1/
management:
  context-path: /admin
  port: 9001

#logging.level.org.springframework.web: DEBUG
#logging.level.org.hibernate: DEBUG
debug: true
trace: false



spring:
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/sb-auth/sb-auth-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    tomcat:
      max-wait: 5000
      max-active: 5
      test-on-borrow: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto:  create
    show-sql: true

logging:
  level:
    root: info
    sbauth: debug
    db.migration: debug
    org.springframework.web: debug
    org.hibernate.SQL: debug
    org.flywaydb.core.Flyway: debug
    org.flywaydb.core.Flyway.*: debug
    org.hibernate.engine.jdbc: debug
    org.hibernate.engine.jdbc.*: debug
 #   org.springframework.beans.factory: debug















