

//#'CREATE TABLE SB_USER22 (   id INT AUTO_INCREMENT,   name  VARCHAR (66) );

create table SB_USER (

  ID bigint generated by default as identity,
  DESCRIPTION varchar(255),
  NAME varchar(255),

  primary key (ID));
